[package]
name = "tracker"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.97"
axum = "0.8.1"
hex = "0.4.3"
serde = { version = "1.0.219", features = ["derive"] }
serde_bencode = "0.2.4"
tokio = { version = "1.44.0", features = ["full"] }
